// // // // // // // // // /////////////////////////////////////////
// BitmapDataPool.as
// Macromedia ActionScript Implementation of the Class BitmapDataPool
// Generated by Enterprise Architect
// Created on:      11-五月-2012 15:20:01
// Original author: ZengFeng
// // // // // // // // // /////////////////////////////////////////
package game.module.map.layers
{
    import flash.display.BitmapData;
    import flash.display.MovieClip;
    import game.module.map.utils.SwfClass;


    /**
     * 固定大小的区块可以从这个池中获取
     * @author ZengFeng
     * @version 1.0
     * @updated 11-五月-2012 15:22:38
     */
    internal class GatePool
    {
        /** 单例对像 */
        private static var _instance : GatePool;

        /** 获取单例对像 */
        static public function get instance() : GatePool
        {
            if (_instance == null)
            {
                _instance = new GatePool(new Singleton());
            }
            return _instance;
        }

        private var list : Vector.<MovieClip> = new Vector.<MovieClip>();

        function GatePool(singleton : Singleton)
        {
        }

        public function getObject() : MovieClip
        {
            if (list.length > 0)
            {
                return list.pop();
            }
            return new SwfClass.Gate();
        }

        /**
         * 
         * @param bitmapData
         */
        public function destoryObject(gete : MovieClip) : void
        {
            if (gete == null) return;
            if (list.indexOf(gete) != -1) return;
            gete.gotoAndStop(1);
            list.push(gete);
        }
    }
    // end BitmapDataPool
}
class Singleton
{
}